version: 2
jobs:
    build:
      branches:
        only:
          - develop
      docker:
        - image: srcml/ubuntu:24.04
      steps:
        - checkout
        - run: apt-get update
        - run: apt-get install -y git ssh xsltproc
        - run: git submodule update --init --recursive
        - run: cmake --workflow --preset ci-ubuntu

