---
name: Build Windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Windows
        uses: microsoft/setup-msbuild@v1

      - name: Create build directory
        shell: bash
        run: |
          mkdir build

      - name: Restore artifacts, or run vcpkg, build (and cache artifacts as post step)
        uses: lukka/run-vcpkg@v10.3
        id: runvcpkg
        with:
          vcpkgGitCommitId: 'acc3bcf76b84ae5041c86ab55fe138ae7b8255c7'
          runVcpkgInstall: true

      - name: CMake Setup on Windows
        shell: bash
        working-directory: build
        run: |
          cmake .. -DCMAKE_TOOLCHAIN_FILE=/c/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        shell: bash
        working-directory: build
        # continue-on-error: true
        run: |
          cmake --build . --config Release

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: Parser
      #     path: build/parser/

      - name: Install on Windows
        shell: bash
        working-directory: build
        run: |
          cmake --build . --config Release --target install

      - name: Set PATH for Windows
        shell: bash
        working-directory: build
        run: |
          echo "/c/Program Files (x86)/srcML/bin" >> $GITHUB_PATH

      - name: Run Installed srcml
        shell: bash
        working-directory: build
        run: |
          srcml --version
          srcml --text="int a;" -l C++
