---
name: Build Windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Windows
        uses: microsoft/setup-msbuild@v1

      - name: Create build directory
        shell: bash
        run: |
          mkdir build
          which vcpkg
          which cmake
          ls -lh /c/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: CMake Setup on Windows
        shell: bash
        working-directory: build
        run: |
          export UseMultiToolTask=true
          cmake .. -DCMAKE_TOOLCHAIN_FILE=/c/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        shell: bash
        working-directory: build
        run: |
          rm -fR D:/a/srcML/srcML/build/deps/tools/
          export UseMultiToolTask=true
          cmake --build . --config Release

      - name: Install on Windows
        shell: bash
        working-directory: build
        run: |
          cmake --build . --config Release --target install

      - name: Set PATH for Windows
        shell: bash
        working-directory: build
        run: |
          echo "/c/Program Files (x86)/srcML/bin" >> $GITHUB_PATH

      - name: Run Installed srcml
        shell: bash
        working-directory: build
        run: |
          srcml --version
          srcml --text="int a;" -l C++
