---
name: Build Windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Windows
        uses: microsoft/setup-msbuild@v1.1

      - name: Create build directory
        shell: bash
        run: |
          mkdir build

      - uses: lukka/get-cmake@latest

      - name: Restore artifacts, or run vcpkg, build (and cache artifacts as post step)
        uses: lukka/run-vcpkg@v10.3
        id: runvcpkg
        with:
          vcpkgGitCommitId: 'acc3bcf76b84ae5041c86ab55fe138ae7b8255c7'
          runVcpkgInstall: true

      # NOTE: this is necessary to correctly find and use cl.exe
      - name: setup devcmd
        uses: ilammy/msvc-dev-cmd@v1

      - name: CMake Setup on Windows
        shell: bash
        working-directory: build
        run: |
          export UseMultiToolTask=true
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl -DDYNAMIC_LOAD_ENABLED=OFF -G "Ninja Multi-Config"

      - name: Build
        shell: bash
        working-directory: build
        continue-on-error: true
        run: |
          export UseMultiToolTask=true
          cmake --build . --config Release

      - name: Package
        working-directory: build
        continue-on-error: true
        run: |
          cpack -G WIX -V

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: CMake
      #     path: build/src/libsrcml/cmake_install.cmake

      - working-directory: build/dist
        run: msiexec /i D:\a\srcML\srcML\build\dist\srcML-Win.msi /quiet /norestart /L*V .\msi.log
      - uses: actions/upload-artifact@v2
        with:
          name: msi.log
          path: build/dist/msi.log

      # - name: Install on Windows
      #   shell: bash
      #   working-directory: build
      #   run: |
      #     cmake --build . --config Release --target install

      - name: Set PATH for Windows
        shell: bash
        working-directory: build
        run: |
          echo "/c/Program Files (x86)/srcML/bin" >> $GITHUB_PATH

      - name: Run Installed srcml
        shell: bash
        working-directory: build
        run: |
          srcml.exe --version
          srcml.exe --text="int a;" -l C++
