---
name: Docker

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup macOS
        shell: bash
        run: |
          brew install docker docker-compose
          echo "cliPluginsExtraDirs": ["/opt/homebrew/lib/docker/cli-plugins"]' >> ~/.docker/config.json
          docker --version
          docker compose --version

      - name: Setup macOS
        shell: bash
        run: |
          docker compose build ubuntu_24.04
