---
name: Test

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Windows
        uses: microsoft/setup-msbuild@v1.1

      - name: Update CMake
        uses: lukka/get-cmake@latest

      - name: Restore artifacts, or run vcpkg, build (and cache artifacts as post step)
        uses: lukka/run-vcpkg@v10.3
        id: runvcpkg
        with:
          vcpkgGitCommitId: 'acc3bcf76b84ae5041c86ab55fe138ae7b8255c7'
          runVcpkgInstall: true

      - name: Setup devcmd to use cl.exe
        uses: ilammy/msvc-dev-cmd@v1

      - name: Create build directory
        shell: bash
        run: |
          mkdir build
          diff --version

      - name: CMake Setup on Windows
        shell: bash
        working-directory: build
        run: |
          echo "HERE: " $VCPKG_INSTALLED_DIR
          ls -lh $VCPKG_INSTALLED_DIR
          export UseMultiToolTask=true
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl -DDYNAMIC_LOAD_ENABLED=OFF -G "Ninja Multi-Config"

      - name: Build
        shell: bash
        working-directory: build
        continue-on-error: true
        run: |
          export UseMultiToolTask=true
          cmake --build . --config Release

      - name: Package
        working-directory: build
        continue-on-error: true
        run: |
          cpack -G WIX -V
      - uses: actions/upload-artifact@v3
        with:
          name: wix.log
          path: build/dist/_CPack_Packages/win64/WIX/wix.log
      - uses: actions/upload-artifact@v3
        with:
          name: srcML-Win
          path: build/dist/srcML-Win.msi

      - working-directory: build/dist
        run: msiexec /i D:\a\srcML\srcML\build\dist\srcML-Win.msi /quiet /norestart /L*vx .\msi.log
      - uses: actions/upload-artifact@v3
        with:
          name: msi.log
          path: build/dist/msi.log

      - name: Set PATH for Windows
        shell: bash
        working-directory: build
        run: |
          echo "/c/Program Files (x86)/srcML/bin" >> $GITHUB_PATH
          echo "/c/Program Files/srcML/bin" >> $GITHUB_PATH

      - name: Run Installed srcml
        shell: bash
        working-directory: build
        run: |
          EOL="\r\n"
          export PATH=$PATH:"/c/Program Files/srcML/bin/"
          SRCML_HOME="/c/Program Files/srcML/bin/"
          ls -lh "$SRCML_HOME"
          SRCML="$SRCML_HOME/srcml.exe"
          ls -lh "$SRCML"
          export MSYS2_ARG_CONV_EXCL="*"
          diff='diff -Z '
          "$SRCML" --version
          "$SRCML" --text="int a;" -l C++
          touch "a.cpp"
          "$SRCML" a.cpp
          echo "a;" >> a.cpp
          "$SRCML" a.cpp
          echo "b;" >> b.cpp
          "$SRCML" a.cpp b.cpp

      - name: Setup msys2 with additional client-test packages for Windows
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            zip
            cpio
            diffutils
            cmake
            util-linux
            libxml2

      - name: Windows Client Tests on Installed srcml
        shell: msys2 {0}
        working-directory: build
        timeout-minutes: 10
        continue-on-error: true
        run: |
          export SRCML_HOME="/c/Program Files/srcML/bin/"
          ctest -C Release -VV

      - uses: actions/upload-artifact@v3
        with:
          name: ClientTest.windows-latest.log
          path: build/Testing/Temporary/LastTest.log

      - name: Build libsrcml Tests
        shell: bash
        working-directory: build
        continue-on-error: true
        run: |
          export UseMultiToolTask=true
          cmake .. -DBUILD_LIBSRCML_TESTS=ON
          cmake --build . --config Release --target build_libsrcml_tests
          dumpbin /dependents bin\Release\test_srcml_read_unit.exe

      - name: Check dependents
        shell: bash
        working-directory: build
        continue-on-error: true
        run: |
          dumpbin /dependents bin\Release\test_srcml_read_unit.exe

      - name: Run libsrcml Tests on Installed libsrcml
        shell: bash
        working-directory: build
        continue-on-error: true
        run: |
          ctest -C Release -R ^test_
      - uses: actions/upload-artifact@v3
        with:
          name: libsrcmlTest.windows-latest.log
          path: build/Testing/Temporary/LastTest.log

      - name: Generate Parser Tests
        shell: bash
        working-directory: build
        run: |
          cmake .. -DBUILD_PARSER_TESTS=ON
          cmake --build . --config Release --target gen_parser_tests

      - name: Run Parser Tests
        shell: bash
        working-directory: build
        continue-on-error: true
        run: |
          srcml --parser-test test/parser/testsuite | tee ParserTest.log
      - uses: actions/upload-artifact@v3
        with:
          name: ParserTest.windows-latest.log
          path: build/ParserTest.log
